In [1]:
i

NameError: name 'i' is not defined

In [2]:
import numpy as np
array_1d=np.array([1,2,3,4,5])
print(array_1d)

[1 2 3 4 5]


In [4]:
import numpy as np
array_2d=np.array([[1,2,3],[4,6,7]])
print(array_2d)

[[1 2 3]
 [4 6 7]]


In [8]:
import numpy as np
array_3d=np.array([[1,2,3],[3,4,5],[5,6,7]])
print(array_3d)

[[1 2 3]
 [3 4 5]
 [5 6 7]]


In [10]:
import pandas  as pd
data=[10,20,30]
series=pd.Series(data,index=['a','b','c'])
print(series)

a    10
b    20
c    30
dtype: int64


In [11]:
import pandas  as pd
data={
    "name":["hi","bye","see"],
    "age":[12,13,14]
}
df=pd.DataFrame(data)
print(df)

  name  age
0   hi   12
1  bye   13
2  see   14


In [15]:
import numpy as np
data=[1,2,3]
mean=np.mean(data)
median=np.median(data)
mode=max(set(data),key=data.count)
print(mean)
print(mode)
print(median)

2.0
1
2.0


In [28]:
import pandas as pd
series=pd.Series(data)
mean=pd.Series(mean)
mode=pd.Series(data).mode()
median=series.median()
print(f"mean is the:",mean)
print("mode is the",mode)
print("median is",median)

mean is the: 0    2.0
dtype: float64
mode is the 0    1
1    2
2    3
dtype: int64
median is 2.0


In [44]:
import pandas as pd
data=pd.read_csv("C:/Users/Rajguru/Downloads/MBA.csv")
discrete_attributes=[]
continuous_attribute=[]
for column in data.columns:
    if data[column].dtype=='object':
        discrete_attributes.append(column)
    elif data[column].dtype in['int64','float64']:
        unique_values=data[column].nunique()
        if unique_values<=10:
            discrete_attributes.append(column)
        else:
            continuous_attribute.append(column)
print("Discrete attributes:")
print(discrete_attributes)
print(continuous_attribute)

Discrete attributes:
['gender', 'major', 'race', 'work_exp', 'work_industry', 'admission']
['application_id', 'gpa', 'gmat']
